language: go
go:
    - tip
    - 1.6
    - 1.5
install:
    - go get github.com/issue9/assert
    - go get github.com/issue9/context
    - go get github.com/issue9/conv
    - go get github.com/issue9/handlers
    - go get github.com/issue9/is
    - go get github.com/issue9/logs
    - go get github.com/issue9/rands
    - go get github.com/issue9/utils
    - go get github.com/issue9/web
